### ISSUE TITLE
[bug] 灵の试炼标签无限循环了

### ISSUE THREAD

**Issue by Chalkydoge** [zhang-wangz/LeetCodeRating#10]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：

环境：Firefox浏览器 + 最新版脚本（支持灵佬文档跳转的版本）
![图片](https://user-images.githubusercontent.com/53142189/194979712-62fb7914-781c-4c19-a6f4-7a877d3ae301.png)

问题：
![图片](https://user-images.githubusercontent.com/53142189/194979359-c56d6a11-84a2-43ad-9e70-faa8dd23c24f.png)

开启脚本，进入页面后会不停的刷undefined 😂 不能正常使用了。。。
会很快就卡死了。感觉是难度那里的逻辑有点问题？（里面混进去一点奇怪的东西。。。

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 环境：Firefox浏览器 + 最新版脚本（支持灵佬文档跳转的版本） ![图片](https://user-images.githubusercontent.com/53142189/194979712-62fb7914-781c-4c19-a6f4-7a877d3ae301.png)
> 
> 问题： ![图片](https://user-images.githubusercontent.com/53142189/194979359-c56d6a11-84a2-43ad-9e70-faa8dd23c24f.png)
> 
> 开启脚本，进入页面后会不停的刷undefined 😂 不能正常使用了。。。 会很快就卡死了。感觉是难度那里的逻辑有点问题？（里面混进去一点奇怪的东西。。。

更新到1.4.4试试。。我刚才就是在修复版本问题，昨天的灵茶有点小问题

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 环境：Firefox浏览器 + 最新版脚本（支持灵佬文档跳转的版本） ![图片](https://user-images.githubusercontent.com/53142189/194979712-62fb7914-781c-4c19-a6f4-7a877d3ae301.png)
> 
> 问题： ![图片](https://user-images.githubusercontent.com/53142189/194979359-c56d6a11-84a2-43ad-9e70-faa8dd23c24f.png)
> 
> 开启脚本，进入页面后会不停的刷undefined 😂 不能正常使用了。。。 会很快就卡死了。感觉是难度那里的逻辑有点问题？（里面混进去一点奇怪的东西。。。

 https://github.com/zhang-wangz/LeetCodeRating/raw/main/leetcodeRating_greasyfork.user.js

**Comment by Chalkydoge** [comment]
给力，刚刚没下载到最新的，fixed
![图片](https://user-images.githubusercontent.com/53142189/194981273-3cbc977d-0ae5-4791-b3e9-4855b0d4edd4.png)

**Comment by GGboya** [comment]
请问这个2100分，是指周赛2100分难度吗，是基于什么预测的呢。我指灵茶。今天一更新插件，看到了这个，不知道难度分是咋来的。

**Comment by zhang-wangz** [comment]
> 请问这个2100分，是指周赛2100分难度吗，是基于什么预测的呢。我指灵茶。今天一更新插件，看到了这个，不知道难度分是咋来的。

codeforce 难度分
