### ISSUE TITLE
[problem]为什么今天老是崩溃掉，是插件的原因还是leetcode呢-力扣更新原因

### ISSUE THREAD

**Issue by GGboya** [zhang-wangz/LeetCodeRating#11]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
今天更新了插件之后，老是遇到leetcode崩溃的问题，不知道是因为插件还是因为leetcode在更新呢。

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 今天更新了插件之后，老是遇到leetcode崩溃的问题，不知道是因为插件还是因为leetcode在更新呢。

能说得再详细一点吗，比如什么浏览器，什么系统，崩溃的截图，目前我在mac 最新版谷歌浏览器下使用没问题

**Comment by GGboya** [comment]
哦哦，昨天崩溃应该是Leetcode更新的问题。不过我还发现下面的bug：
![image](https://user-images.githubusercontent.com/92285610/195233494-0d6d0127-1658-4cde-bbf9-454abaca343e.png)
企业题库里面，难度分显示的地方显示错了。
如果不加载插件，是这样：
![image](https://user-images.githubusercontent.com/92285610/195233600-a6c72170-da42-48f3-b20f-7d4f5c1e7bb3.png)

**Comment by zhang-wangz** [comment]
> 哦哦，昨天崩溃应该是Leetcode更新的问题。不过我还发现下面的bug： ![image](https://user-images.githubusercontent.com/92285610/195233494-0d6d0127-1658-4cde-bbf9-454abaca343e.png) 企业题库里面，难度分显示的地方显示错了。 如果不加载插件，是这样： ![image](https://user-images.githubusercontent.com/92285610/195233600-a6c72170-da42-48f3-b20f-7d4f5c1e7bb3.png)

力扣加了新东西。。谢谢提醒，我待会改一下

**Comment by zhang-wangz** [comment]
> 哦哦，昨天崩溃应该是Leetcode更新的问题。不过我还发现下面的bug： ![image](https://user-images.githubusercontent.com/92285610/195233494-0d6d0127-1658-4cde-bbf9-454abaca343e.png) 企业题库里面，难度分显示的地方显示错了。 如果不加载插件，是这样： ![image](https://user-images.githubusercontent.com/92285610/195233600-a6c72170-da42-48f3-b20f-7d4f5c1e7bb3.png)

主要企业是另一个人写的，我没有会员改不了，如果待会改不了可能就去处企业页面的功能了

**Comment by zhang-wangz** [comment]
> 哦哦，昨天崩溃应该是Leetcode更新的问题。不过我还发现下面的bug： ![image](https://user-images.githubusercontent.com/92285610/195233494-0d6d0127-1658-4cde-bbf9-454abaca343e.png) 企业题库里面，难度分显示的地方显示错了。 如果不加载插件，是这样： ![image](https://user-images.githubusercontent.com/92285610/195233600-a6c72170-da42-48f3-b20f-7d4f5c1e7bb3.png)

加个微信吧，待会我改一下你帮我看一下。。heymanwz
