### ISSUE TITLE
主页面没有显示灵神试炼，还有页面的竞赛分数没有显示 - 用户无法访问raw.githubusercontent的问题，自行解决

### ISSUE THREAD

**Issue by FantasticCode2019** [zhang-wangz/LeetCodeRating#12]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
![image](https://user-images.githubusercontent.com/53119335/198866185-ab9d5382-4031-41ea-9727-283d5ce572c7.png)

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> ![image](https://user-images.githubusercontent.com/53119335/198866185-ab9d5382-4031-41ea-9727-283d5ce572c7.png)

你好，升级到最新版1.4.9了吗, 同时啥浏览器

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> ![image](https://user-images.githubusercontent.com/53119335/198866185-ab9d5382-4031-41ea-9727-283d5ce572c7.png)
如果你用的是1.4.9以前的版本是因为我用的版本管理的网站维护了几个礼拜了，所以茶数据和难度分数据获取不了，需要手动更新下最新版

**Comment by FantasticCode2019** [comment]
使用的浏览器是Edge，脚本是开启的
脚本的版本是1.4.9

**Comment by FantasticCode2019** [comment]
刚刚重新安装了脚本，还是不行

**Comment by zhang-wangz** [comment]
> 刚刚重新安装了脚本，还是不行

https://raw.githubusercontent.com/zhang-wangz/LeetCodeRating/main/version.json

**Comment by FantasticCode2019** [comment]
不能访问，那请问一下，可否以后支持cdn

**Comment by zhang-wangz** [comment]
> 不能访问，那请问一下，可否以后支持cdn

这得看cdn的修复时间了，我也是倾向于使用cdn的，但是维护时间已经接近一个礼拜，目前不清楚是否可以使用了以后

**Comment by zhang-wangz** [comment]
> 不能访问，那请问一下，可否以后支持cdn

可以按照这个链接尝试 https://www.jianshu.com/p/51decd726dd1
