### ISSUE TITLE
对应周赛链接存在问题

### ISSUE THREAD

**Issue by KargathEx** [zhang-wangz/LeetCodeRating#13]
update: 打扰抱歉，看来显示不了是因为中文站没有对应的周赛。
一点建议:获取中文站的最早一个周赛场次，如果当前的场次比它小则跳到主站去。
这样至少比一直显示空白好一点,没有错误提示的话会以为自己的网速有问题。

### 请描述你遇到的问题：
比如对于 [此题目](https://leetcode.cn/problems/global-and-local-inversions/),插件显示为 `第69场周赛Q2`,点进去之后会一直[刷不出东西](https://leetcode.cn/contest/weekly-contest-69)。
原因是leetcode中文站只有一部分周赛，剩下的在主站才有。
而对应的[双周赛](https://leetcode.cn/contest/biweekly-contest-69/) 是多出来一个`bi`的。

不懂这个标签怎么搞，这个应该是bug 而非 [help wanted]、

**Comment by zhang-wangz** [comment]
> update: 打扰抱歉，看来显示不了是因为中文站没有对应的周赛。 一点建议:获取中文站的最早一个周赛场次，如果当前的场次比它小则跳到主站去。 这样至少比一直显示空白好一点,没有错误提示的话会以为自己的网速有问题。
> 
> ### 请描述你遇到的问题：
> 比如对于 [此题目](https://leetcode.cn/problems/global-and-local-inversions/),插件显示为 `第69场周赛Q2`,点进去之后会一直[刷不出东西](https://leetcode.cn/contest/weekly-contest-69)。 原因是leetcode中文站只有一部分周赛，剩下的在主站才有。 而对应的[双周赛](https://leetcode.cn/contest/biweekly-contest-69/) 是多出来一个`bi`的。
> 
> 不懂这个标签怎么搞，这个应该是bug 而非 [help wanted]、

是的，写的时候就已经注明了这个问题，这个q2主要还是让大家对题目处于第几题有个了解，链接是其次的

**Comment by zhang-wangz** [comment]
> update: 打扰抱歉，看来显示不了是因为中文站没有对应的周赛。 一点建议:获取中文站的最早一个周赛场次，如果当前的场次比它小则跳到主站去。 这样至少比一直显示空白好一点,没有错误提示的话会以为自己的网速有问题。
> 
> ### 请描述你遇到的问题：
> 比如对于 [此题目](https://leetcode.cn/problems/global-and-local-inversions/),插件显示为 `第69场周赛Q2`,点进去之后会一直[刷不出东西](https://leetcode.cn/contest/weekly-contest-69)。 原因是leetcode中文站只有一部分周赛，剩下的在主站才有。 而对应的[双周赛](https://leetcode.cn/contest/biweekly-contest-69/) 是多出来一个`bi`的。
> 
> 不懂这个标签怎么搞，这个应该是bug 而非 [help wanted]、
我联系下，看看能不能解决吧

**Comment by zhang-wangz** [comment]
> update: 打扰抱歉，看来显示不了是因为中文站没有对应的周赛。 一点建议:获取中文站的最早一个周赛场次，如果当前的场次比它小则跳到主站去。 这样至少比一直显示空白好一点,没有错误提示的话会以为自己的网速有问题。
> 
> ### 请描述你遇到的问题：
> 比如对于 [此题目](https://leetcode.cn/problems/global-and-local-inversions/),插件显示为 `第69场周赛Q2`,点进去之后会一直[刷不出东西](https://leetcode.cn/contest/weekly-contest-69)。 原因是leetcode中文站只有一部分周赛，剩下的在主站才有。 而对应的[双周赛](https://leetcode.cn/contest/biweekly-contest-69/) 是多出来一个`bi`的。
> 
> 不懂这个标签怎么搞，这个应该是bug 而非 [help wanted]、

修复了，这个缺陷，就按照你的来

**Comment by KargathEx** [comment]
谢谢
