### ISSUE TITLE
题目搜索结果页没有显示难度分

### ISSUE THREAD

**Issue by EndlessCheng** [zhang-wangz/LeetCodeRating#14]
https://leetcode.cn/search/?q=2000

**Comment by zhang-wangz** [comment]
> https://leetcode.cn/search/?q=2000

这个页面是哪里进去的呀= =

**Comment by EndlessCheng** [comment]
> > https://leetcode.cn/search/?q=2000
> 
> 这个页面是哪里进去的呀, 我没有找到进入这个页面的入口

主页右上搜索框

**Comment by zhang-wangz** [comment]
> > > https://leetcode.cn/search/?q=2000
> > 
> > 
> > 这个页面是哪里进去的呀, 我没有找到进入这个页面的入口
> 
> 主页右上搜索框

在讨论右上找到啦，最近有点忙，有时间补上

**Comment by zhang-wangz** [comment]
> https://leetcode.cn/search/?q=2000

已更新
