### ISSUE TITLE
有没有计划支持国际服啊？

### ISSUE THREAD

**Issue by ThomasShaw1** [zhang-wangz/LeetCodeRating#15]
[> 添加vx heymanwz 可直接与作者沟通

**Comment by zhang-wangz** [comment]
> [> 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：](https://leetcode.com/discuss/general-discussion/2949463/Feature-request-Add-Rating-to-the-questions)

暂时不支持，但是如果有需要的可以和我联系，其实只要改动一些小地方就可以支持国际服

**Comment by zhang-wangz** [comment]
只是我最近没啥时间

**Comment by zhang-wangz** [comment]
> [> 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：](https://leetcode.com/discuss/general-discussion/2949463/Feature-request-Add-Rating-to-the-questions)

已支持，由一个小伙伴完成了，直接在github 切换tag为english 按照操作步骤即可使用
