### ISSUE TITLE
更新之后, 点开题目页面不再显示是周赛哪道题以及难度分

### ISSUE THREAD

**Issue by Ryanbaiyansong** [zhang-wangz/LeetCodeRating#16]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
<img width="459" alt="image" src="https://user-images.githubusercontent.com/43448174/218277775-e6026cbd-fa31-488d-b6b6-9dd3c74f62d6.png">

**Comment by zhang-wangz** [comment]
什么版本，什么系统的，我这边没遇到诶，版本1.7.9

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> <img alt="image" width="459" src="https://user-images.githubusercontent.com/43448174/218277775-e6026cbd-fa31-488d-b6b6-9dd3c74f62d6.png">

什么版本，什么系统的，我这边没遇到诶，版本1.7.9

**Comment by zhang-wangz** [comment]
我先关闭了，没回复的话
