### ISSUE TITLE
提交时间功能

### ISSUE THREAD

**Issue by lx-1005** [zhang-wangz/LeetCodeRating#18]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
我使用的旧版UI, 提交代码之后, 我不希望看到本次提交花费的时间,  如果有可能的话, 可以单独设置一个开关吗?因为右下角的时间显示我还是挺喜欢的
![image](https://user-images.githubusercontent.com/57821029/219999561-99272e64-4e1d-41ed-95f1-02373961e25a.png)
![image](https://user-images.githubusercontent.com/57821029/219999584-53204631-40e0-41f3-9c77-d1cc59022c6d.png)

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 我使用的旧版UI, 提交代码之后, 我不希望看到本次提交花费的时间, 如果有可能的话, 可以单独设置一个开关吗?因为右下角的时间显示我还是挺喜欢的 ![image](https://user-images.githubusercontent.com/57821029/219999561-99272e64-4e1d-41ed-95f1-02373961e25a.png) ![image](https://user-images.githubusercontent.com/57821029/219999584-53204631-40e0-41f3-9c77-d1cc59022c6d.png)

该功能我已经不再处理啦，这个本身是少康的项目 https://github.com/XYShaoKang/refined-leetcode 生成的， 他之前没有设置开关，我才拦截了一下他的计时器功能，现在他的插件已经有开关了，我在之前的版本里面已经将拦截去除了，这个功能需求你可以在他的项目下提一下issue(虽然我也能在我的插件里做到，但是不太好)

**Comment by lx-1005** [comment]
好的了解了, 非常感谢
