### ISSUE TITLE
【求助】1.8.3版本题库等所有页面都不显示分数-网络环境问题

### ISSUE THREAD

**Issue by Charlie6000** [zhang-wangz/LeetCodeRating#19]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
如题，1.8.3版本题库等所有页面都不显示分数，请问是配置问题还是其他问题？谢谢！
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/20102036/220005341-6750c414-9510-421b-8a94-6894b9085507.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/20102036/220005465-3ba3cc96-20b4-467c-ab3f-00d995a6e865.png">

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 如题，1.8.3版本题库等所有页面都不显示分数，请问是配置问题还是其他问题？谢谢！ <img alt="image" width="1784" src="https://user-images.githubusercontent.com/20102036/220005341-6750c414-9510-421b-8a94-6894b9085507.png"> <img alt="image" width="557" src="https://user-images.githubusercontent.com/20102036/220005465-3ba3cc96-20b4-467c-ab3f-00d995a6e865.png">

脚本问题，已经紧急打tag了，1.8.4刚修复，是因为油猴官方不允许导入github js文件导致的，有问题可以再反馈

**Comment by Charlie6000** [comment]
> 

谢谢回复！我升级到1.8.4，但是还是不显示

**Comment by Charlie6000** [comment]
> > > 添加vx heymanwz 可直接与作者沟通
> > 
> > 
> > ### 请描述你遇到的问题：
> > 如题，1.8.3版本题库等所有页面都不显示分数，请问是配置问题还是其他问题？谢谢！ <img alt="image" width="1784" src="https://user-images.githubusercontent.com/20102036/220005341-6750c414-9510-421b-8a94-6894b9085507.png"> <img alt="image" width="557" src="https://user-images.githubusercontent.com/20102036/220005465-3ba3cc96-20b4-467c-ab3f-00d995a6e865.png">
> 
> 脚本问题，已经紧急打tag了，1.8.4刚修复，是因为油猴官方不允许导入github js文件导致的，有问题可以再反馈


谢谢回复！我升级到1.8.4，但是还是不显示
