### ISSUE TITLE
UI 建议

### ISSUE THREAD

**Issue by EndlessCheng** [zhang-wangz/LeetCodeRating#2]
对于具体的题目页面：

1. 在难度分没有的情况下，不显示「难度分未知」。
2. 如果有难度分，可以直接替换「简单」「中等」「困难」为难度分。

**Comment by zhang-wangz** [comment]
1.2.0 修改pb UI，和题库页面保持一致，有难度分直接替换原本的难度标识

**Comment by zhang-wangz** [comment]
end
