### ISSUE TITLE
周赛排名界面不显示使用哪种语言和分数预测-refined-leetcode问题

### ISSUE THREAD

**Issue by lx-1005** [zhang-wangz/LeetCodeRating#21]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
之前刚装这个插件的时候, 周赛排名界面可以预测分数变化, 以及每个人每道题使用哪种语言AC的, 现在不显示了. 是脚本更新的原因吗?
![image](https://user-images.githubusercontent.com/57821029/221499741-d07afdca-4467-4f4d-b238-9bf49431761b.png)

**Comment by lx-1005** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 之前刚装这个插件的时候, 周赛排名界面可以预测分数变化, 以及每个人每道题使用哪种语言AC的, 现在不显示了. 是脚本更新的原因吗? ![image](https://user-images.githubusercontent.com/57821029/221499741-d07afdca-4467-4f4d-b238-9bf49431761b.png)

我重装插件也不行, 我应该怎么做?

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 之前刚装这个插件的时候, 周赛排名界面可以预测分数变化, 以及每个人每道题使用哪种语言AC的, 现在不显示了. 是脚本更新的原因吗? ![image](https://user-images.githubusercontent.com/57821029/221499741-d07afdca-4467-4f4d-b238-9bf49431761b.png)

这个功能是https://github.com/XYShaoKang/refined-leetcode产生的, 可以去那里提一下issue，可能出问题了，虽然我也能做，但是功能重复不太好
