### ISSUE TITLE
竞赛页上的 container 多出一层黄色背景且布局错乱

### ISSUE THREAD

**Issue by Yescafe** [zhang-wangz/LeetCodeRating#22]
### 请描述你遇到的问题：

所有会影响到力扣网页的插件均己关闭，也没有安装其它的油猴脚本。

![image](https://user-images.githubusercontent.com/25558466/223095230-35d9fb7b-2522-45d1-9db1-76df911b9824.png)

![image](https://user-images.githubusercontent.com/25558466/223095358-90730b17-f9d9-4bfb-8849-260a20dcef1c.png)

![image](https://user-images.githubusercontent.com/25558466/223095306-769aeacb-8899-4ac2-93a2-7cd97fc93a68.png)

![image](https://user-images.githubusercontent.com/25558466/223095632-4b63c0f0-7688-411d-b161-7816634edb9a.png)

container 上会被增加一层奇怪的东西，把这两个属性注释掉就正常了：

![image](https://user-images.githubusercontent.com/25558466/223096159-35017b5c-f0ce-45e2-bfc9-0aab051d5319.png)

系统是 macOS 13，浏览器是 Microsoft Edge。

**Comment by Yescafe** [comment]
看上去像是这次改动出现的问题 4cab8b5

**Comment by zhang-wangz** [comment]
> ### 请描述你遇到的问题：
> 所有会影响到力扣网页的插件均己关闭，也没有安装其它的油猴脚本。
> 
> ![image](https://user-images.githubusercontent.com/25558466/223095230-35d9fb7b-2522-45d1-9db1-76df911b9824.png)
> 
> ![image](https://user-images.githubusercontent.com/25558466/223095358-90730b17-f9d9-4bfb-8849-260a20dcef1c.png)
> 
> ![image](https://user-images.githubusercontent.com/25558466/223095306-769aeacb-8899-4ac2-93a2-7cd97fc93a68.png)
> 
> ![image](https://user-images.githubusercontent.com/25558466/223095632-4b63c0f0-7688-411d-b161-7816634edb9a.png)
> 
> container 上会被增加一层奇怪的东西，把这两个属性注释掉就正常了：
> 
> ![image](https://user-images.githubusercontent.com/25558466/223096159-35017b5c-f0ce-45e2-bfc9-0aab051d5319.png)
> 
> 系统是 macOS 13，浏览器是 Microsoft Edge。

是的，确实是，是因为css id冲突导致的，待会马上改，谢谢

**Comment by Yescafe** [comment]
> > ### 请描述你遇到的问题：
> > 所有会影响到力扣网页的插件均己关闭，也没有安装其它的油猴脚本。
> > ![image](https://user-images.githubusercontent.com/25558466/223095230-35d9fb7b-2522-45d1-9db1-76df911b9824.png)
> > ![image](https://user-images.githubusercontent.com/25558466/223095358-90730b17-f9d9-4bfb-8849-260a20dcef1c.png)
> > ![image](https://user-images.githubusercontent.com/25558466/223095306-769aeacb-8899-4ac2-93a2-7cd97fc93a68.png)
> > ![image](https://user-images.githubusercontent.com/25558466/223095632-4b63c0f0-7688-411d-b161-7816634edb9a.png)
> > container 上会被增加一层奇怪的东西，把这两个属性注释掉就正常了：
> > ![image](https://user-images.githubusercontent.com/25558466/223096159-35017b5c-f0ce-45e2-bfc9-0aab051d5319.png)
> > 系统是 macOS 13，浏览器是 Microsoft Edge。
> 
> 是的，确实是，是因为css id冲突导致的，待会马上改，谢谢

好的，非常感谢，您做的插件真的非常好用！

**Comment by zhang-wangz** [comment]
> > > ### 请描述你遇到的问题：
> > > 所有会影响到力扣网页的插件均己关闭，也没有安装其它的油猴脚本。
> > > ![image](https://user-images.githubusercontent.com/25558466/223095230-35d9fb7b-2522-45d1-9db1-76df911b9824.png)
> > > ![image](https://user-images.githubusercontent.com/25558466/223095358-90730b17-f9d9-4bfb-8849-260a20dcef1c.png)
> > > ![image](https://user-images.githubusercontent.com/25558466/223095306-769aeacb-8899-4ac2-93a2-7cd97fc93a68.png)
> > > ![image](https://user-images.githubusercontent.com/25558466/223095632-4b63c0f0-7688-411d-b161-7816634edb9a.png)
> > > container 上会被增加一层奇怪的东西，把这两个属性注释掉就正常了：
> > > ![image](https://user-images.githubusercontent.com/25558466/223096159-35017b5c-f0ce-45e2-bfc9-0aab051d5319.png)
> > > 系统是 macOS 13，浏览器是 Microsoft Edge。
> > 
> > 
> > 是的，确实是，是因为css id冲突导致的，待会马上改，谢谢
> 
> 好的，非常感谢，您做的插件真的非常好用！

谢谢肯定，1.8.9 已解决
