### ISSUE TITLE
新版本 Chrome 显示不出来？-浏览器阻止了js，css加载

### ISSUE THREAD

**Issue by OliverChao** [zhang-wangz/LeetCodeRating#23]
### 请描述你遇到的问题：

新版本 v1.8.8 不能正常显示？ 而且，打开插件经常不显示一些配置

### chrome版本截图
![image](https://user-images.githubusercontent.com/39361033/223117365-1fad3ecf-d3c7-41ce-868f-f5b8528f491b.png)
![image](https://user-images.githubusercontent.com/39361033/223117746-e326ca60-b8a7-490f-8fa3-12140f9834c6.png)

### edge截图
![image](https://user-images.githubusercontent.com/39361033/223117472-c4e8fc1e-5e2a-4862-8385-8a45150a4f94.png)

![image](https://user-images.githubusercontent.com/39361033/223117787-185a87f5-7a2f-4702-8b50-9e730da89080.png)

chrome版本：
Version 110.0.5481.177 (Official Build) (64-bit)

操作系统：
Ubuntu 22.04

**Comment by zhang-wangz** [comment]
f12有没有报错啥的看看

**Comment by OliverChao** [comment]
![image](https://user-images.githubusercontent.com/39361033/223121840-f0ebbaed-4bc8-4c91-8511-24c9403de1f5.png)

**Comment by zhang-wangz** [comment]
> ![image](https://user-images.githubusercontent.com/39361033/223121840-f0ebbaed-4bc8-4c91-8511-24c9403de1f5.png)

是的，这就是你这个浏览器有问题，应该是禁止了jquery的加载

**Comment by zhang-wangz** [comment]
> ![image](https://user-images.githubusercontent.com/39361033/223121840-f0ebbaed-4bc8-4c91-8511-24c9403de1f5.png)

你加我微信吧，heymanwz

**Comment by xuyanshi** [comment]
I have the same question.


CHROME VERSION  | 113.0.5672.63
-- | --
OS VERSION | Mac OS X: 13.3.1
cpu_arch   | arm64

**Comment by zhang-wangz** [comment]
> I have the same question.
> 
> CHROME VERSION	113.0.5672.63
> OS VERSION	Mac OS X: 13.3.1
> cpu_arch  	arm64

f12 截图看看

**Comment by zhang-wangz** [comment]
> > > I have the same question.
> > > CHROME VERSION	113.0.5672.63
> > > OS VERSION	Mac OS X: 13.3.1
> > > cpu_arch  	arm64
> > 
> > 
> > f12 截图看看
> 
> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/36392244/236770509-91d94370-d0b3-4bf2-ace7-84763faae071.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/49056179/236770918-d4060773-8a74-464f-8988-14f9dca7d7b2.png">
点进去看看，看看是哪行报错了

**Comment by xuyanshi** [comment]
> > > > I have the same question.
> > > > CHROME VERSION	113.0.5672.63
> > > > OS VERSION	Mac OS X: 13.3.1
> > > > cpu_arch  	arm64
> > > 
> > > 
> > > f12 截图看看
> > 
> > 
> > <img alt="image" width="1280" src="https://user-images.githubusercontent.com/36392244/236770509-91d94370-d0b3-4bf2-ace7-84763faae071.png">
> 
> <img alt="image" width="929" src="https://user-images.githubusercontent.com/49056179/236770918-d4060773-8a74-464f-8988-14f9dca7d7b2.png">
> 
> 点进去看看，看看是哪行报错了

报错点在这里，但是这边都挤在同一行了，我也不知道具体错误是什么。

<img width="835" alt="image" src="https://user-images.githubusercontent.com/36392244/236778603-d14d724d-937f-4042-af40-1c5cb7a37ddf.png">

**Comment by zhang-wangz** [comment]
> > > > > I have the same question.
> > > > > CHROME VERSION	113.0.5672.63
> > > > > OS VERSION	Mac OS X: 13.3.1
> > > > > cpu_arch  	arm64
> > > > 
> > > > 
> > > > f12 截图看看
> > > 
> > > 
> > > <img alt="image" width="1280" src="https://user-images.githubusercontent.com/36392244/236770509-91d94370-d0b3-4bf2-ace7-84763faae071.png">
> > 
> > 
> > <img alt="image" width="929" src="https://user-images.githubusercontent.com/49056179/236770918-d4060773-8a74-464f-8988-14f9dca7d7b2.png">
> > 点进去看看，看看是哪行报错了
> 
> 报错点在这里，但是这边都挤在同一行了，我也不知道具体错误是什么。
> 
> <img alt="image" width="835" src="https://user-images.githubusercontent.com/36392244/236778603-d14d724d-937f-4042-af40-1c5cb7a37ddf.png">

你的网络代理有问题，https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js 这个访问不了，要不就是开了全局vpn，要不就是科学上网的设置不太对

**Comment by zhang-wangz** [comment]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/49056179/236780807-54b38fd0-953d-4e0d-b414-810b873d7600.png">
对应的是脚本里的第26行，这个没加载导致消息组建里面用到jquery的时候找不到定义报错的

**Comment by xuyanshi** [comment]
> <img alt="image" width="1029" src="https://user-images.githubusercontent.com/49056179/236780807-54b38fd0-953d-4e0d-b414-810b873d7600.png">
> 
> 对应的是脚本里的第26行，这个没加载导致消息组件里面用到jquery的时候找不到定义报错的

Thanks. 🙏
