### ISSUE TITLE
[bug] 灵茶翻译部分 转义的小bug

### ISSUE THREAD

**Issue by Chalkydoge** [zhang-wangz/LeetCodeRating#24]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：

03.13茶的题干没有展示完整；
发现是`containerlingtea`内容框内部的 中文翻译符号转义错误 
把'<'识别成htmltag的一部分，导致题目渲染被吞了一部分

<img width="966" alt="掉格式" src="https://user-images.githubusercontent.com/53142189/224628003-a8d0c1ff-82a5-4071-9f35-e6f418f7144b.png">

### 需要的修改

`checktrans`函数把所有的`'<','>'`都转义一下就好啦😀
之前是`replace` 但是实际上可能有很多个符号，所以需要`replaceAll`

![image](https://user-images.githubusercontent.com/53142189/224627396-d2092cc8-ce86-4221-955e-c9a2ec392af6.png)

修改之后

<img width="479" alt="image" src="https://user-images.githubusercontent.com/53142189/224628194-fc2c288a-d8c9-4250-8e65-d5a3f59c9c21.png">

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 03.13茶的题干没有展示完整； 发现是`containerlingtea`内容框内部的 中文翻译符号转义错误 把'<'识别成htmltag的一部分，导致题目渲染被吞了一部分
> 
> <img alt="掉格式" width="966" src="https://user-images.githubusercontent.com/53142189/224628003-a8d0c1ff-82a5-4071-9f35-e6f418f7144b.png">
> 
> ### 需要的修改
> `checktrans`函数把所有的`'<','>'`都转义一下就好啦😀 之前是`replace` 但是实际上可能有很多个符号，所以需要`replaceAll`
> 
> ![image](https://user-images.githubusercontent.com/53142189/224627396-d2092cc8-ce86-4221-955e-c9a2ec392af6.png)
> 
> 修改之后
> 
> <img alt="image" width="479" src="https://user-images.githubusercontent.com/53142189/224628194-fc2c288a-d8c9-4250-8e65-d5a3f59c9c21.png">

谢谢大佬，直接提个pull request吧，我merge...这种翻译总是防不胜防

**Comment by Chalkydoge** [comment]
> > > 添加vx heymanwz 可直接与作者沟通
> > 
> > 
> > ### 请描述你遇到的问题：
> > 03.13茶的题干没有展示完整； 发现是`containerlingtea`内容框内部的 中文翻译符号转义错误 把'<'识别成htmltag的一部分，导致题目渲染被吞了一部分
> > <img alt="掉格式" width="966" src="https://user-images.githubusercontent.com/53142189/224628003-a8d0c1ff-82a5-4071-9f35-e6f418f7144b.png">
> > ### 需要的修改
> > `checktrans`函数把所有的`'<','>'`都转义一下就好啦😀 之前是`replace` 但是实际上可能有很多个符号，所以需要`replaceAll`
> > ![image](https://user-images.githubusercontent.com/53142189/224627396-d2092cc8-ce86-4221-955e-c9a2ec392af6.png)
> > 修改之后
> > <img alt="image" width="479" src="https://user-images.githubusercontent.com/53142189/224628194-fc2c288a-d8c9-4250-8e65-d5a3f59c9c21.png">
> 
> 谢谢大佬，直接提个pull request吧，我merge...这种翻译总是防不胜防

thx, 已提pr 就一行改动😂
