### ISSUE TITLE
使用此插件是否符合官方规定-符合

### ISSUE THREAD

**Issue by KargathEx** [zhang-wangz/LeetCodeRating#27]
### 请描述你遇到的问题：
注意到官网更新了[条款](https://leetcode.cn/terms/)，有一条是
>3.1.7. 不得使用未经力扣授权或许可的任何插件、外挂、系统或第三方工具对“力扣”及相关服务的正常运行进行干扰、破坏、修改或施加其他影响。

请问使用此插件是否属于以上情况？

**Comment by zhang-wangz** [comment]
> ### 请描述你遇到的问题：
> 注意到官网更新了[条款](https://leetcode.cn/terms/)，有一条是
> 
> > 3.1.7. 不得使用未经力扣授权或许可的任何插件、外挂、系统或第三方工具对“力扣”及相关服务的正常运行进行干扰、破坏、修改或施加其他影响。
> 
> 请问使用此插件是否属于以上情况？
我也注意到了，目前还不知道，在群里问客服呢，不管怎么样我自己肯定还是在用的，如果有不符合的估计会修改下release的版本吧

**Comment by zhang-wangz** [comment]
> ### 请描述你遇到的问题：
> 注意到官网更新了[条款](https://leetcode.cn/terms/)，有一条是
> 
> > 3.1.7. 不得使用未经力扣授权或许可的任何插件、外挂、系统或第三方工具对“力扣”及相关服务的正常运行进行干扰、破坏、修改或施加其他影响。
> 
> 请问使用此插件是否属于以上情况？

收到回复了，这条款原来就有，没太大的影响，放心用
