### ISSUE TITLE
userscript.html大量错误, 好像是一个Dom操作错误-插件打印log排错，慢是edge渲染的问题

### ISSUE THREAD

**Issue by ruibin** [zhang-wangz/LeetCodeRating#28]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
console.log()很多错误, 1秒钟10几个吧, 时间久了会导致页面变卡!
<img width="557" alt="Leetcode_Rating_错误" src="https://github.com/zhang-wangz/LeetCodeRating/assets/2504901/1eb3755d-9d79-4008-9251-82a81fbc3812">

<img width="571" alt="Leetcode_Rating_colorSpan错误" src="https://github.com/zhang-wangz/LeetCodeRating/assets/2504901/f92cfed3-5bca-4c34-9bc4-be9008c746f0">

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> console.log()很多错误, 1秒钟10几个吧, 时间久了会导致页面变卡! <img alt="Leetcode_Rating_错误" width="557" src="https://user-images.githubusercontent.com/2504901/240267187-1eb3755d-9d79-4008-9251-82a81fbc3812.png">
> 
> <img alt="Leetcode_Rating_colorSpan错误" width="571" src="https://user-images.githubusercontent.com/2504901/240267225-f92cfed3-5bca-4c34-9bc4-be9008c746f0.png">
新版还是旧版，电脑环境，什么浏览器，什么场景下

**Comment by zhang-wangz** [comment]
> > > 添加vx heymanwz 可直接与作者沟通
> > 
> > 
> > ### 请描述你遇到的问题：
> > console.log()很多错误, 1秒钟10几个吧, 时间久了会导致页面变卡! <img alt="Leetcode_Rating_错误" width="557" src="https://user-images.githubusercontent.com/2504901/240267187-1eb3755d-9d79-4008-9251-82a81fbc3812.png">
> > <img alt="Leetcode_Rating_colorSpan错误" width="571" src="https://user-images.githubusercontent.com/2504901/240267225-f92cfed3-5bca-4c34-9bc4-be9008c746f0.png">
> 
> 新版还是旧版，电脑环境，什么浏览器，什么场景下



> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> console.log()很多错误, 1秒钟10几个吧, 时间久了会导致页面变卡! <img alt="Leetcode_Rating_错误" width="557" src="https://user-images.githubusercontent.com/2504901/240267187-1eb3755d-9d79-4008-9251-82a81fbc3812.png">
> 
> <img alt="Leetcode_Rating_colorSpan错误" width="571" src="https://user-images.githubusercontent.com/2504901/240267225-f92cfed3-5bca-4c34-9bc4-be9008c746f0.png">

因为很多人来提问题都不带日志，就直接硬问，所以错误就直接打印了，有错误就关闭对应的功能来提问好了

**Comment by ruibin** [comment]
Mac系统, Edge浏览器版本 114.0.1823.24 (正式版本) , 插件是最新版
