### ISSUE TITLE
提交页面的备注信息重叠了

### ISSUE THREAD

**Issue by john9999911** [zhang-wangz/LeetCodeRating#29]
### 正常情况下：
![image](https://github.com/zhang-wangz/LeetCodeRating/assets/80616586/96da0098-d667-455b-913d-e2bbb1708255)

### 开启题目页评分和新版提交信息后：
![image](https://github.com/zhang-wangz/LeetCodeRating/assets/80616586/5ca9b614-0a58-46c5-9196-3e7eb5636f1f)

**Comment by john9999911** [comment]
已经排除了其他插件造成的影响。

**Comment by zhang-wangz** [comment]
> 已经排除了其他插件造成的影响。

力扣改板块了 = =，之前是这样的，然后前几天改成span了，今天又改回来了，这前端真会玩

**Comment by zhang-wangz** [comment]
> 已经排除了其他插件造成的影响。

1.10.4已修复
