### ISSUE TITLE
如何恢复旧版提交界面ui？

### ISSUE THREAD

**Issue by zowei** [zhang-wangz/LeetCodeRating#33]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
![image](https://github.com/zhang-wangz/LeetCodeRating/assets/36793718/edb235b9-9ba3-4df6-bc63-85b78d0676f1)
hello ？ 这是您的新版提交页面ui，能否恢复到旧版本的那种呢？类似下面这种
![image](https://github.com/zhang-wangz/LeetCodeRating/assets/36793718/ea00fd48-6a61-479c-abf1-527b5a4b6159)

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> ![image](https://user-images.githubusercontent.com/36793718/253749380-edb235b9-9ba3-4df6-bc63-85b78d0676f1.png) hello ？ 这是您的新版提交页面ui，能否恢复到旧版本的那种呢？类似下面这种 ![image](https://user-images.githubusercontent.com/36793718/253749419-ea00fd48-6a61-479c-abf1-527b5a4b6159.png)

无法恢复, 可以做出来(重新覆盖官方画界面),
但是最根本的原因是力扣官方换版了, 插件只是为了适配官方增加功能, 而不是颠覆(所以只是重新适配了现在的页面)
加上题目页已经开了内测, 没有多久就完全不一样了,所以就没考虑花更多的精力重画覆盖它.
这一块我也向官方提交了修改意见, 官方已经在做调整了, 后续内容应该会重新补充上

**Comment by zowei** [comment]
好的，那就等官方调整吧，感谢
