### ISSUE TITLE
关于题库页面难度分筛选搜索功能

### ISSUE THREAD

**Issue by ReiiNoki** [zhang-wangz/LeetCodeRating#34]
我记得之前用过的版本是在题库页面有一个难度分筛选和题单制作的功能的，现在的版本是删除了吗？

**Comment by zhang-wangz** [comment]
> 我记得之前用过的版本是在题库页面有一个难度分筛选和题单制作的功能的，现在的版本是删除了吗？

https://github.com/XYShaoKang/refined-leetcode/tree/master

**Comment by ReiiNoki** [comment]
不是您的脚本有的功能吗...那是我记错了很抱歉

**Comment by zhang-wangz** [comment]
> 不是您的脚本有的功能吗...那是我记错了很抱歉

没事,经常有人搞混= =
