### ISSUE TITLE
获取节点失败 应当不执行

### ISSUE THREAD

**Issue by wuxin0011** [zhang-wangz/LeetCodeRating#45]
> 添加vx heymanwz 可直接与作者沟通

###  控制台报错会造成有一点卡顿：
[随便一个题目](https://leetcode.cn/problems/numbers-with-repeated-digits/)

### 没有判断节点是否存在，不断重复获取 
![image](https://github.com/zhang-wangz/LeetCodeRating/assets/65836396/0390bacc-3d0e-47c0-8e90-20b753e7a340)

代码`1246` 行和 `1254`行

`1246`
```js

 let pbarr = overflow?.childNodes[0]?.childNodes[1]?.childNodes[0];
  if(!pbarr){
     return;
  }
```

`1254`
```js
let pbName = onepb?.childNodes[0]?.childNodes[1]?.childNodes[0]?.textContent
if(!pbName){
    continue;
}
```

![image](https://github.com/zhang-wangz/LeetCodeRating/assets/65836396/d4088be4-196e-4472-af92-dd8df2dfadb7)

**Comment by zhang-wangz** [comment]
2.1.8 已修复

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 控制台报错会造成有一点卡顿：
> [随便一个题目](https://leetcode.cn/problems/numbers-with-repeated-digits/)
> 
> ### 没有判断节点是否存在，不断重复获取
> ![image](https://private-user-images.githubusercontent.com/65836396/298255748-0390bacc-3d0e-47c0-8e90-20b753e7a340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTgxNjQsIm5iZiI6MTcxMjgxNzg2NCwicGF0aCI6Ii82NTgzNjM5Ni8yOTgyNTU3NDgtMDM5MGJhY2MtM2QwZS00N2MwLThlOTAtMjBiNzUzZTdhMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA2NDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YjRiMzczZjNkZjhkNTNhYzRkYTZjZTM5ZTZiMzMyMjRhZTA5YTA1NzRiZDQyOTk5NzcxMmM0ZTVjMzYzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kaAbrt00tTjrneHsodi0jbZMV5G6Yx38XWBNcGbiS2M)
> 
> 代码`1246` 行和 `1254`行
> 
> `1246`
> 
> ```js
>  let pbarr = overflow?.childNodes[0]?.childNodes[1]?.childNodes[0];
>   if(!pbarr){
>      return;
>   }
> ```
> 
> `1254`
> 
> ```js
> let pbName = onepb?.childNodes[0]?.childNodes[1]?.childNodes[0]?.textContent
> if(!pbName){
>     continue;
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/65836396/298255618-d4088be4-196e-4472-af92-dd8df2dfadb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTgxNjQsIm5iZiI6MTcxMjgxNzg2NCwicGF0aCI6Ii82NTgzNjM5Ni8yOTgyNTU2MTgtZDQwODhiZTQtMTk2ZS00NDcyLWFmOTItZGQ4ZGYyZGZhZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA2NDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZjk4MmZmMjcxOTU1YTQ3MmE4Nzg0YzBjM2YzNDQ3ZGM1MGYxYTg1NWU3MGQ4ZTVmN2NlZjRmZDdkMzJkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.16piA055LUWaLjmVv-vS9B0wLGKro07tAjlqsPCIkNM)

2.1.8 已修复
