### ISSUE TITLE
油叉2.1.4

### ISSUE THREAD

**Issue by Ebbjik** [zhang-wangz/LeetCodeRating#46]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
油叉2.1.4版本（最新），不管在哪个界面都不显示分数了（）

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 油叉2.1.4版本（最新），不管在哪个界面都不显示分数了（）

单纯今天每日一题没有分数罢了。。。

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 油叉2.1.4版本（最新），不管在哪个界面都不显示分数了（）

发你一个以前的题，https://leetcode.cn/problems/find-the-k-or-of-an-array/?envType=daily-question&envId=2024-03-17
