### ISSUE TITLE
火狐浏览器开启深色模式显示异常

### ISSUE THREAD

**Issue by syz521** [zhang-wangz/LeetCodeRating#48]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
火狐版本：kali linux 115.8.0esr (64-bit)
插件版本: 2.1.6
Tampermonkey版本: 5.1.0
问题表现：更新到最新版的插件后，浏览器开启深色模式无法看清题目。

**Comment by zhang-wangz** [comment]
找到问题了，2.1.7等会发

> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 火狐版本：kali linux 115.8.0esr (64-bit) 插件版本: 2.1.6 Tampermonkey版本: 5.1.0 问题表现：更新到最新版的插件后，浏览器开启深色模式无法看清题目。

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 火狐版本：kali linux 115.8.0esr (64-bit) 插件版本: 2.1.6 Tampermonkey版本: 5.1.0 问题表现：更新到最新版的插件后，浏览器开启深色模式无法看清题目。

已经解决
