### ISSUE TITLE
复制去除版权信息出错

### ISSUE THREAD

**Issue by msccreater** [zhang-wangz/LeetCodeRating#51]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
复制代码编辑区域自己写的代码，代码太长的话会导致复制的内容不全，中间大部分会删掉变成（...）

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 复制代码编辑区域自己写的代码，代码太长的话会导致复制的内容不全，中间大部分会删掉变成（...）

有链接吗

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 复制代码编辑区域自己写的代码，代码太长的话会导致复制的内容不全，中间大部分会删掉变成（...）

找到了，原来是自己写代码的那块

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 复制代码编辑区域自己写的代码，代码太长的话会导致复制的内容不全，中间大部分会删掉变成（...）

2.2.2 fix
