### ISSUE TITLE
请问使用插件后，之前做过题代码就不会显示了吗？

### ISSUE THREAD

**Issue by peng-yq** [zhang-wangz/LeetCodeRating#53]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
没用插件之前，点击做过的题目，代码一般会显示在旁边；而现在需要去提交记录中查看

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> 没用插件之前，点击做过的题目，代码一般会显示在旁边；而现在需要去提交记录中查看

不会的，是不是你更新了浏览器或者删除了浏览记录啥的，力扣的记录是保存在本地的，如果做了上面的操作，就需要重新加载

**Comment by peng-yq** [comment]
> > > 添加vx heymanwz 可直接与作者沟通
> > 
> > 
> > ### 请描述你遇到的问题：
> > 没用插件之前，点击做过的题目，代码一般会显示在旁边；而现在需要去提交记录中查看
> 
> 不会的，是不是你更新了浏览器或者删除了浏览记录啥的，力扣的记录是保存在本地的，如果做了上面的操作，就需要重新加载

好的，感谢回复
