### ISSUE TITLE
算术难度为空

### ISSUE THREAD

**Issue by shawnau** [zhang-wangz/LeetCodeRating#56]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
![image](https://github.com/user-attachments/assets/2d811f63-84ab-4440-b144-86335e5c9312)

当前使用版本: 2.3.7

**Comment by zhang-wangz** [comment]
企鹅群 654726006

**Comment by shawnau** [comment]
好像是我的误解, 因为这道题不在周赛里所以这里没有显示周赛题号和难度.
不过算术难度为空, 所以修改了问题

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> ![image](https://private-user-images.githubusercontent.com/11170898/352982865-378e5ffc-7007-45d1-905c-5c60ade01311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDQwNTksIm5iZiI6MTcyMjI0Mzc1OSwicGF0aCI6Ii8xMTE3MDg5OC8zNTI5ODI4NjUtMzc4ZTVmZmMtNzAwNy00NWQxLTkwNWMtNWM2MGFkZTAxMzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA5MDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiM2Y5ZTg4ODI4YzgxMzllMDgxNGE0M2IxMjhkZjFjNTlkMWJiYjkwNTczMjU4YzU5MWNjMTczOTc2YzM0NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sg6KNqkdeDqY-sG_yLEXys1PI7y6ItgmYS6ukUfers0) 题目状态无法显示, 点击同步题目状态之后没有变化
> 
> 当前使用版本: 2.3.7

加群说吧，这个图也看不出啥问题，这个题目本来就没有算数分的，同步题目状态是讨论区的ac状态

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：
> ![image](https://private-user-images.githubusercontent.com/11170898/352984227-2d811f63-84ab-4440-b144-86335e5c9312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDQxNDQsIm5iZiI6MTcyMjI0Mzg0NCwicGF0aCI6Ii8xMTE3MDg5OC8zNTI5ODQyMjctMmQ4MTFmNjMtODRhYi00NDQwLWIxNDQtODYzMzVlNWM5MzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA5MDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDJjN2YyZDUyYzkyYjk4ZmQ1YmYwNmQ1MWVjYmVlZGU5ODNiYWU0OGJkM2NmMmIxZjA1YTlhMjNjZDFmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2gTbmimeIk2z_7bK7fiy48_1sxzsj2bGBhn6i0D4Mw)
> 
> 当前使用版本: 2.3.7

好像确实是我设计2.3.1那个显示题目完成状态时候，不小心把说明给删了，补丁包2.3.8已经改了，刚发布
