### ISSUE TITLE
关于更新提示的问题

### ISSUE THREAD

**Issue by Ben-Lee-2019** [zhang-wangz/LeetCodeRating#57]
hi，你好 ，感谢编写这个插件让我们刷题更加轻松，想提一个小小的需求
![image](https://github.com/user-attachments/assets/5738b831-6ac2-44d8-9b23-1e72c9f17ac0)
目前插件更新会弹出界面提示，只要不更新每次刷新或打开界面就会弹出来一次，能否关闭这个提示或者让它最多只弹出一次呢

**Comment by zhang-wangz** [comment]
> hi，你好 ，感谢编写这个插件让我们刷题更加轻松，想提一个小小的需求 ![image](https://private-user-images.githubusercontent.com/56856471/353667603-5738b831-6ac2-44d8-9b23-1e72c9f17ac0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTI4MzIsIm5iZiI6MTcyMjM5MjUzMiwicGF0aCI6Ii81Njg1NjQ3MS8zNTM2Njc2MDMtNTczOGI4MzEtNmFjMi00NGQ4LTliMjMtMWU3MmM5ZjE3YWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAyMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMTkxYmJlZDExNjA5MjA0OTNiZmM1MDE2MWUxNzVhM2YzZTEzZDU3ZTA1NzNjYzJiMWM3OTljYzVmYmM1YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1hySPxSauFec9o0T4wRMogZnRjvrAGWyR2JX0wLQJVk) 目前插件更新会弹出界面提示，只要不更新每次刷新或打开界面就会弹出来一次，能否关闭这个提示或者让它最多只弹出一次呢

因为最近新功能的问题，所以更新比较多，到后面稳定了基本上几个月不会有变动～ 估摸着也就频繁一个礼拜多点，或许后面可能考虑出个按钮可以暂时不接受任何更新，但缺点就是如果一直屏蔽着就无法更新了

**Comment by Ben-Lee-2019** [comment]
> > hi，你好 ，感谢编写这个插件让我们刷题更加轻松，想提一个小小的需求 ![image](https://private-user-images.githubusercontent.com/56856471/353667603-5738b831-6ac2-44d8-9b23-1e72c9f17ac0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTI4MzIsIm5iZiI6MTcyMjM5MjUzMiwicGF0aCI6Ii81Njg1NjQ3MS8zNTM2Njc2MDMtNTczOGI4MzEtNmFjMi00NGQ4LTliMjMtMWU3MmM5ZjE3YWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAyMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMTkxYmJlZDExNjA5MjA0OTNiZmM1MDE2MWUxNzVhM2YzZTEzZDU3ZTA1NzNjYzJiMWM3OTljYzVmYmM1YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1hySPxSauFec9o0T4wRMogZnRjvrAGWyR2JX0wLQJVk) 目前插件更新会弹出界面提示，只要不更新每次刷新或打开界面就会弹出来一次，能否关闭这个提示或者让它最多只弹出一次呢
> 
> 因为最近新功能的问题，所以更新比较多，到后面稳定了基本上几个月不会有变动～ 估摸着也就频繁一个礼拜多点，或许后面可能考虑出个按钮可以暂时不接受任何更新，但缺点就是如果一直屏蔽着就无法更新了

了解了，感谢
