### ISSUE TITLE
暗色主题下，弹出框的文字无法正常显示

### ISSUE THREAD

**Issue by mingyEx** [zhang-wangz/LeetCodeRating#59]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：
<img width="394" alt="80d7124cdfb7ed229585da5aea02dbb" src="https://github.com/user-attachments/assets/da086336-2184-4b62-bfb7-38562319872b">
如图

**Comment by zhang-wangz** [comment]
2.4.3 修复
