### ISSUE TITLE
[bug]当 hover 题目后面的反馈按钮的时候会不断的添加周赛 link

### ISSUE THREAD

**Issue by fengwei2002** [zhang-wangz/LeetCodeRating#6]
当 hover 题目后面的反馈按钮的时候（不触发点击事件）

例如： 

![image](https://user-images.githubusercontent.com/56250171/189520423-7304e9e6-7c70-4057-91d7-cda1fa4db419.png)

会直接在原有周赛链接之后再次 append 一个新的周赛元素 

![image](https://user-images.githubusercontent.com/56250171/189520435-ce7aca04-590d-4ce5-936d-d77f7daf2f20.png)

hover 一次就会新创建一个元素

应该是创建周赛元素的逻辑存在一些问题

**Comment by zhang-wangz** [comment]
感谢，我在发布新版本之前也遇到过一次这个问题，但是后面无论都复现不了，稍后修复

**Comment by zhang-wangz** [comment]
明白了，是触发了力扣设定的鼠标hover事件，导致判断的条件被强行改变了

**Comment by fengwei2002** [comment]
👍

**Comment by zhang-wangz** [comment]
1.2.6 已修复
