### ISSUE TITLE
题解复制去尾巴功能失效

### ISSUE THREAD

**Issue by LionfishLion** [zhang-wangz/LeetCodeRating#61]
> 添加vx heymanwz 可直接与作者沟通

### 请描述你遇到的问题：题解复制去尾巴功能失效
无论是点击复制按钮复制还是鼠标拖动复制 粘贴代码后仍会出现版权信息

**Comment by zhang-wangz** [comment]
> > 添加vx heymanwz 可直接与作者沟通
> 
> ### 请描述你遇到的问题：题解复制去尾巴功能失效
> 无论是点击复制按钮复制还是鼠标拖动复制 粘贴代码后仍会出现版权信息

已解决
