### ISSUE TITLE
【功能建议】能否加一个筛选会员题的功能

### ISSUE THREAD

**Issue by adanzl** [zhang-wangz/LeetCodeRating#9]
现在不能筛选会员题，实在是不方便，总要换页，不知道能否实现

**Comment by zhang-wangz** [comment]
不好实现，会出现每一页的数据只有一两条的情况(因为插件的修改是基于服务器传回来的数据进行修改的
这个需求我之前已经了解过了，想过另一种思路就是使用力扣的开放api，但是发现也没有提供专属会员筛题的功能

**Comment by zhang-wangz** [comment]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/49056179/191185545-f9a0b980-8a76-4305-9220-6c7e3f205334.png">
其实力扣已经提供了plus会员题的功能，个人感觉足够了

**Comment by zhang-wangz** [comment]
> 现在不能筛选会员题，实在是不方便，总要换页，不知道能否实现
<img width="849" alt="image" src="https://user-images.githubusercontent.com/49056179/191185545-f9a0b980-8a76-4305-9220-6c7e3f205334.png">
其实力扣已经提供了plus会员题的功能，个人感觉足够了

**Comment by zhang-wangz** [comment]
> 现在不能筛选会员题，实在是不方便，总要换页，不知道能否实现
<img width="849" alt="image" src="https://user-images.githubusercontent.com/49056179/191185545-f9a0b980-8a76-4305-9220-6c7e3f205334.png">
其实力扣已经提供了plus会员题的功能，个人感觉足够了
